"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const steps = ["Company", "Business", "Goals", "Ready"];
const goals = ["Organize sales", "Capture leads", "Book appointments", "Improve customer service", "Plan marketing"];

export default function OnboardingPage() {
  const router = useRouter(); const [step, setStep] = useState(0); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [data, setData] = useState({ company_name: "", legal_name: "", primary_domain: "", timezone: "America/Chicago", industry: "", team_size: "solo", phone: "", website: "", goals: [] as string[] });
  function update(name: string, value: string) { setData(previous => ({ ...previous, [name]: value })); }
  function toggleGoal(goal: string) { setData(previous => ({ ...previous, goals: previous.goals.includes(goal) ? previous.goals.filter(item => item !== goal) : [...previous.goals, goal] })); }
  async function submit(event: FormEvent) { event.preventDefault(); if (step < 3) { setStep(value => value + 1); return; } setBusy(true); setError(""); try { const response = await fetch("/api/onboarding", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { error?: string; redirect?: string }; if (!response.ok) throw new Error(result.error || "Could not save onboarding."); router.push(result.redirect || "/workspace.html"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save onboarding."); setBusy(false); } }
  return <main className="onboarding-page"><section className="onboarding-shell"><header><span className="auth-brand">SaaS Launchup</span><span className="onboarding-count">Step {step + 1} of {steps.length}</span></header><div className="onboarding-progress">{steps.map((label, index) => <span className={index <= step ? "active" : ""} key={label}>{label}</span>)}</div><form onSubmit={submit} className="onboarding-form">
    {step === 0 ? <><p className="auth-kicker">Workspace foundation</p><h1>Tell us about your company.</h1><p className="auth-copy">This information powers your CRM, reports, forms, and company settings.</p><label>Company name<input value={data.company_name} onChange={event => update("company_name", event.target.value)} required /></label><label>Legal name<input value={data.legal_name} onChange={event => update("legal_name", event.target.value)} /></label><label>Company website<input type="url" placeholder="https://example.com" value={data.website} onChange={event => update("website", event.target.value)} /></label></> : null}
    {step === 1 ? <><p className="auth-kicker">Operating context</p><h1>How does your team work?</h1><label>Industry<input value={data.industry} onChange={event => update("industry", event.target.value)} required placeholder="SaaS, consulting, healthcare..." /></label><label>Team size<select value={data.team_size} onChange={event => update("team_size", event.target.value)}><option value="solo">Just me</option><option value="2-10">2-10 people</option><option value="11-50">11-50 people</option><option value="51-200">51-200 people</option><option value="201+">201+ people</option></select></label><label>Company phone<input type="tel" value={data.phone} onChange={event => update("phone", event.target.value)} placeholder="+1 555 123 4567" /></label><label>Timezone<select value={data.timezone} onChange={event => update("timezone", event.target.value)}><option>America/Chicago</option><option>America/New_York</option><option>America/Denver</option><option>America/Los_Angeles</option><option>UTC</option></select></label></> : null}
    {step === 2 ? <><p className="auth-kicker">First outcomes</p><h1>What should SaaS Launchup help with?</h1><p className="auth-copy">Choose everything that matters right now.</p><div className="goal-grid">{goals.map(goal => <button type="button" className={data.goals.includes(goal) ? "goal selected" : "goal"} onClick={() => toggleGoal(goal)} key={goal}>{goal}</button>)}</div></> : null}
    {step === 3 ? <><p className="auth-kicker">Ready to launch</p><h1>Your workspace is ready to configure.</h1><p className="auth-copy">We will create your company workspace with the details you provided. You can connect Twilio, forms, calendars, and other services from Settings.</p><div className="onboarding-summary"><strong>{data.company_name || "Your company"}</strong><span>{data.industry || "Industry not set"} · {data.team_size}</span><span>{data.goals.length ? data.goals.join(" · ") : "No goals selected"}</span></div></> : null}
    {error ? <p className="auth-error" role="alert">{error}</p> : null}<div className="onboarding-actions">{step > 0 ? <button type="button" className="auth-secondary" onClick={() => setStep(value => value - 1)}>Back</button> : null}<button type="submit" disabled={busy}>{busy ? "Saving..." : step === 3 ? "Open my workspace" : "Continue"}</button></div>
  </form></section></main>;
}
